In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
X_train

array([[7.6, 3. , 6.6, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [4.8, 3.1, 1.6, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.4, 1.5, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.2, 3.5, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6. , 3.4, 4.5, 1.6],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 2. , 3.5, 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [6.3, 2.7, 4.9, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.3, 3.7, 1.5, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.5, 2.4, 3.7, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.1, 2.8, 4. , 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 3. , 4.9, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2

In [8]:
X_train_scaled

array([[ 2.12367745, -0.12622549,  1.60059596,  1.16454615],
       [-1.4039586 ,  0.33983786, -1.39522226, -1.31228708],
       [-0.43081762, -1.52441554,  0.01789954, -0.13905029],
       [-1.28231598,  0.10680618, -1.22564764, -1.31228708],
       [ 1.02889385,  0.57286953,  1.09187211,  1.16454615],
       [-1.03903073,  0.80590121, -1.28217251, -1.31228708],
       [ 0.29903811, -1.05835219,  1.03534724,  0.25202865],
       [-0.55246024,  1.97105959, -1.39522226, -1.0515678 ],
       [-0.18753238,  1.73802791, -1.16912277, -1.18192744],
       [-0.79574549,  1.03893289, -1.28217251, -1.31228708],
       [ 0.05575287, -0.12622549,  0.75272288,  0.77346722],
       [-1.03903073,  0.80590121, -1.22564764, -1.0515678 ],
       [ 0.66396598,  0.33983786,  0.86577262,  1.42526544],
       [ 0.54232336, -1.29138387,  0.69619801,  0.90382687],
       [ 0.17739549,  0.80590121,  0.41357365,  0.51274793],
       [-1.64724384, -1.75744722, -1.39522226, -1.18192744],
       [-1.03903073, -2.

In [10]:
import numpy as np

(X_train - np.mean(X_train, axis = 0)) / np.std(X_train, axis = 0)
# axis =0, we want it per feature, not the whole
# divide by standard deviation
# should be the same (??) as standard scaler

array([[ 2.12367745, -0.12622549,  1.60059596,  1.16454615],
       [-1.4039586 ,  0.33983786, -1.39522226, -1.31228708],
       [-0.43081762, -1.52441554,  0.01789954, -0.13905029],
       [-1.28231598,  0.10680618, -1.22564764, -1.31228708],
       [ 1.02889385,  0.57286953,  1.09187211,  1.16454615],
       [-1.03903073,  0.80590121, -1.28217251, -1.31228708],
       [ 0.29903811, -1.05835219,  1.03534724,  0.25202865],
       [-0.55246024,  1.97105959, -1.39522226, -1.0515678 ],
       [-0.18753238,  1.73802791, -1.16912277, -1.18192744],
       [-0.79574549,  1.03893289, -1.28217251, -1.31228708],
       [ 0.05575287, -0.12622549,  0.75272288,  0.77346722],
       [-1.03903073,  0.80590121, -1.22564764, -1.0515678 ],
       [ 0.66396598,  0.33983786,  0.86577262,  1.42526544],
       [ 0.54232336, -1.29138387,  0.69619801,  0.90382687],
       [ 0.17739549,  0.80590121,  0.41357365,  0.51274793],
       [-1.64724384, -1.75744722, -1.39522226, -1.18192744],
       [-1.03903073, -2.

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
X_train_scaled
# no negative value

array([[0.91428571, 0.45454545, 0.94915254, 0.83333333],
       [0.08571429, 0.54545455, 0.05084746, 0.04166667],
       [0.31428571, 0.18181818, 0.47457627, 0.41666667],
       [0.11428571, 0.5       , 0.10169492, 0.04166667],
       [0.65714286, 0.59090909, 0.79661017, 0.83333333],
       [0.17142857, 0.63636364, 0.08474576, 0.04166667],
       [0.48571429, 0.27272727, 0.77966102, 0.54166667],
       [0.28571429, 0.86363636, 0.05084746, 0.125     ],
       [0.37142857, 0.81818182, 0.11864407, 0.08333333],
       [0.22857143, 0.68181818, 0.08474576, 0.04166667],
       [0.42857143, 0.45454545, 0.69491525, 0.70833333],
       [0.17142857, 0.63636364, 0.10169492, 0.125     ],
       [0.57142857, 0.54545455, 0.72881356, 0.91666667],
       [0.54285714, 0.22727273, 0.6779661 , 0.75      ],
       [0.45714286, 0.63636364, 0.59322034, 0.625     ],
       [0.02857143, 0.13636364, 0.05084746, 0.08333333],
       [0.17142857, 0.        , 0.42372881, 0.375     ],
       [0.48571429, 0.40909091,

In [14]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

# training data - minimum
(X_train - X_min) / (X_max - X_min)

array([[0.91428571, 0.45454545, 0.94915254, 0.83333333],
       [0.08571429, 0.54545455, 0.05084746, 0.04166667],
       [0.31428571, 0.18181818, 0.47457627, 0.41666667],
       [0.11428571, 0.5       , 0.10169492, 0.04166667],
       [0.65714286, 0.59090909, 0.79661017, 0.83333333],
       [0.17142857, 0.63636364, 0.08474576, 0.04166667],
       [0.48571429, 0.27272727, 0.77966102, 0.54166667],
       [0.28571429, 0.86363636, 0.05084746, 0.125     ],
       [0.37142857, 0.81818182, 0.11864407, 0.08333333],
       [0.22857143, 0.68181818, 0.08474576, 0.04166667],
       [0.42857143, 0.45454545, 0.69491525, 0.70833333],
       [0.17142857, 0.63636364, 0.10169492, 0.125     ],
       [0.57142857, 0.54545455, 0.72881356, 0.91666667],
       [0.54285714, 0.22727273, 0.6779661 , 0.75      ],
       [0.45714286, 0.63636364, 0.59322034, 0.625     ],
       [0.02857143, 0.13636364, 0.05084746, 0.08333333],
       [0.17142857, 0.        , 0.42372881, 0.375     ],
       [0.48571429, 0.40909091,